---
Title: "Proyecto Comercio - FASE 2 - 2018 - 2024"
author: "Fredy Picen"
date: "2025-11-25"
output: html_document
---

```{r setup, eval=FALSE}

#Librerias

library(readxl)
library(arules)
library(genero)
library(rpart)
library(rpart.plot)
library(randomForest)
library(readxl)
library(dplyr)
library(arules)
library(ggplot2)
library(knitr)
opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(echo = TRUE)

```



```{r Integracion DS IMPORTS, eval=FALSE}

ruta <- "C:/Users/fredy/Documents/Maestria Ciencias Computacion Ciencia Datos/4. Cuarto Trimestre/Introduccion Mineria de Datos/Proyecto Final/Fase 1/Importaciones"

archivos_ini <- list.files(path = ruta, pattern = "\\.xlsx$", full.names = TRUE)
print(archivos_ini)

#Uniendo todos los archivos
dataset_imports <- archivos_ini %>%
  lapply(read_excel) %>%
  bind_rows()
  print(dataset_imports)
  
```


```{r Integracion DS EXPORTS, eval=FALSE}
library(readxl)
library(dplyr)

ruta_2 <- "C:/Users/fredy/Documents/Maestria Ciencias Computacion Ciencia Datos/4. Cuarto Trimestre/Introduccion Mineria de Datos/Proyecto Final/Fase 1/Exportaciones"

archivos_ini1 <- list.files(path = ruta_2, pattern = "\\.xlsx$", full.names = TRUE)
print(archivos_ini1)

#Uniendo todos los archivos
dataset_exports <- archivos_ini1 %>%
  lapply(read_excel) %>%
  bind_rows()
  print(dataset_exports)

```

**Arboles de Decision**

```{r Arboles de Decision DS Import, eval=FALSE}
# Exploración inicial de la variable objetivo

cat("Distribución de Pais:\n")
table(dataset_imports$PAIS)
cat("\n")

```
```{r, eval=FALSE}
# ÁRBOL DE DECISIÓN

# relación PAIS-IMPORTACIONES basado en:
# - características de la importacion (Valor, Peso, Via, Aduana, Sac, Mes y Año)
# - con esto, la prediccion sera mas soportada y nos dara informacion relevante.

tree <- rpart(PAIS ~
              VALOR +
              PESO +
              VIA +
              ADUANA +
              SAC +
              MES +
              ANYO,
            data = dataset_imports, 
            method = "class",
            control = rpart.control(
              minsplit = 200,   
              minbucket = 100,  
              maxdepth = 4,    
              cp = 0.01
            ))

```

```{r, eval=FALSE}
#Graficando el arbol de decision.

rpart.plot(tree, type = 2, extra = 0, under = TRUE, box.palette = "BuGn",
            main= "PAIS", cex= 0.5)

#El resultado evidencia que con base en el pais, el arbol crece en funcion de la aduana, evidenciando que efectivamente las rutas tiene una relevancia incluso desde que procedencia es la carga.


```
```{r, eval=FALSE}
cat("\nImportancia de las variables:\n")
print(tree$variable.importance)

cat("\n ---- RESUMEN DEL MODELO ---- \n")
print(summary(tree))

## A continuacion, el codigo anteirior nos dara inshights o referencias relevantes del arbol lo que nos puede 

```
```{r, eval=FALSE}

# - Se realiza la prediccion

Importp <- data.frame(
    VALOR = 10000000,
    PESO = 20000000,
    VIA = 3,
    ADUANA = 11,
    SAC = 8465,
    MES = 8,
    ANYO = 2018
)

```


```{r, eval=FALSE}
predic <- predict(tree, Importp, type = "prob")

cat("\n### PREDICCIÓN PARA PAIS ###\n")
cat("Valor de la importacion: 100,000 USD\n")
cat("- Peso de la importacion: 1,200 Kg\n")
cat("- Medio de Transporte: Aereo\n")
cat("- Aduana: Express Aereo\n")
cat("- Sac: Maquinas Herramienta(8465)\n")
cat("- Mes: Agosto\n")
cat("- Año: 2018\n")
cat("\n")

```

```{r, eval=FALSE}

##Presentacion del resultado de la prediccion

cat("Probabilidades de Pais:\n")
print(round(predic * 100, 2))

# El codigo de abajo filtra y nos permite identificar la relación más probable

relacion_antic <- colnames(predic)[which.max(predic)]
prob_maxima <- max(predic) * 100

cat("\nRelación más probable:", relacion_antic)
cat("\nProbabilidad:", round(prob_maxima, 2), "%\n")



```

**VARIABLE 2**

```{r Arboles de Decision 2, eval=FALSE}
# EXploración inicial de la variable objetivo

cat("Distribución de SAC:\n")
table(dataset_imports$SAC)
cat("\n")

```

```{r, eval=FALSE}
# ÁRBOL DE DECISIÓN

# relación SAC-IMPORTACIONES basado en:
# - características de la importacion (Valor, Peso, Via, Aduana, Pais, Mes y Año)
# - con esto, la prediccion sera mas soportada y nos dara informacion relevante.

tree2 <- rpart(SAC ~
              VALOR +
              PESO +
              VIA +
              ADUANA +
              PAIS +
              MES +
              ANYO,
            data = dataset_imports, 
            method = "class",
            control = rpart.control(
              minsplit = 200,   
              minbucket = 100,  
              maxdepth = 4,    
              cp = 0.01
            ))

```

```{r, eval=FALSE}

rpart.plot(tree2, type = 2, extra = 0, under = TRUE, box.palette = "BuGn",
            main= "SAC", cex= 0.5)

#El resultado evidencia que con base en el la SAC(Partida Arancelaria), no genera un arbol.


```


```{r, eval=FALSE}
cat("\nImportancia de las variables:\n")
print(tree2$variable.importance)

cat("\n---- RESUMEN DEL MODELO ---- \n")
print(summary(tree2))

```


```{r, eval=FALSE}

Importp1 <- data.frame(
    VALOR = 1000000,
    PESO = 20000,
    VIA = 3,
    ADUANA = 11,
    PAIS = 5404,
    MES = 10,
    ANYO = 2019
)

```


```{r, eval=FALSE}
predic1 <- predict(tree2, Importp1, type = "prob")

cat("\n### PREDICCIÓN PARA PAIS ###\n")
cat("Valor de la importacion: 100,000 USD\n")
cat("- Peso de la importacion: 1,200 Kg\n")
cat("- Medio de Transporte: Aereo\n")
cat("- Aduana: Express Aereo\n")
cat("- Sac: Maquinas Herramienta(8465)\n")
cat("- Mes: Agosto\n")
cat("- Año: 2018\n")
cat("\n")

```

```{r, eval=FALSE}

cat("Probabilidades de Pais:\n")
print(round(predic1 * 100, 2))

# identificar la relación más probable
relacion_antic1 <- colnames(predic1)[which.max(predic1)]
prob_maxima1 <- max(predic1) * 100

cat("\nRelación más probable:", relacion_antic1)
cat("\nProbabilidad:", round(prob_maxima1, 2), "%\n")



```

**VARIABLE 3**

```{r Arboles de Decision3, eval=FALSE}

# EXploración inicial de la variable objetivo

cat("Distribución de ADUANA:\n")
table(dataset_imports$ADUANA)
cat("\n")

```

```{r, eval=FALSE}

# ÁRBOL DE DECISIÓN

# relación ADUANA-IMPORTACIONES basado en:
# - características de la importacion (Valor, Peso, Via, Aduana, Pais, Mes y Año)
# - con esto, la prediccion sera mas soportada y nos dara informacion relevante.


tree3 <- rpart(ADUANA ~
              VALOR +
              PESO +
              VIA +
              SAC +
              PAIS +
              MES +
              ANYO,
            data = dataset_imports, 
            method = "class",
            control = rpart.control(
              minsplit = 200,   
              minbucket = 100,  
              maxdepth = 4,    
              cp = 0.01
            ))

```

```{r, eval=FALSE}

rpart.plot(tree3, type = 2, extra = 0, under = TRUE, box.palette = "BuGn",
            main= "ADUANA", cex= 0.5)

#El resultado del grafico evidencia que cuando se evalua el dataset desde la Aduana, la relacion mas fuerte que exite es la Via, esto confirma lo que se enconto en la fase 1 que la infraestructura vial o canales logisticos son de suma importancia.

```



```{r, eval=FALSE}

cat("\nImportancia de las variables:\n")
print(tree3$variable.importance)

cat("\n---- RESUMEN DEL MODELO ----\n")
print(summary(tree3))

```


```{r, eval=FALSE}

#Se buscara predecir la siguiente importacion.

Importp3 <- data.frame(
    VALOR = 10000000,
    PESO = 20000000,
    VIA = 3,
    PAIS = 5404,
    SAC = 4012,
    MES = 7,
    ANYO = 2024
)
```


```{r, eval=FALSE}

predic3 <- predict(tree3, Importp3, type = "prob")

cat("\n### PREDICCIÓN PARA ADUANA ###\n")
cat("- Valor de la importacion: 10,000,000 USD\n")
cat("- Peso de la importacion: 20,000,000 Kg\n")
cat("- Medio de Transporte: Marino\n")
cat("- Pais: China\n")
cat("- Sac: Neumaticos\n")
cat("- Mes: Julio\n")
cat("- Año: 2024 \n")
cat("\n")

```

```{r, eval=FALSE}
# Se presentan la prediccion para Aduana 

cat("Probabilidades de Aduana:\n")
print(round(predic3 * 100, 2))

# Relación más probable

relacion_antic3 <- colnames(predic3)[which.max(predic3)]
prob_maxima3 <- max(predic3) * 100

cat("\nRelación más probable:", relacion_antic3)
cat("\nProbabilidad:", round(prob_maxima3, 2), "%\n")

# El puerto que mas se usa para este tipo de importaciones es PUERTO QUETZAL, desde China.

```

**ARBO DE DECISION - EXPORT**
**VARIABLE 4 EXPORTS**

```{r Arboles de Decision4, eval=FALSE}
# EXploración inicials de la variable objetivo

cat("Distribución de SAC:\n")
table(dataset_exports$SAC)
cat("\n")

```

```{r, eval=FALSE}
# ÁRBOL DE DECISIÓN

# relación víctima-agresor basado en:
# - características de la víctima (sexo, edad, escolaridad, estado civil)
# - características del agresor (sexo, edad, escolaridad)
# - contexto del hecho (área, departamento)

tree4 <- rpart(SAC ~
              VALOR +
              PESO +
              VIA +
              ADUANA +
              PAIS +
              MES +
              ANYO,
            data = dataset_exports, 
            method = "class",
            control = rpart.control(
              minsplit = 200,   
              minbucket = 100,  
              maxdepth = 4,    
              cp = 0.01
            ))

```

```{r, eval=FALSE}
rpart.plot(tree, 
           type = 4,              
           extra = 2,
           under = FALSE,         
           fallen.leaves = TRUE, 
           box.palette = "RdYlGn",
           main = "",
           cex = 0.8,
           tweak = 1.3,
           clip.right.labs = FALSE,
           varlen = 0,
           faclen = 0)

rpart.plot(tree4, type = 2, extra = 0, under = TRUE, box.palette = "BuGn",
            main= "SAC EXPORT", cex= 0.5)



```



```{r, eval=FALSE}
cat("\nImportancia de las variables:\n")
print(tree4$variable.importance)

cat("\n=== RESUMEN DEL MODELO ===\n")
print(summary(tree4))

```


```{r, eval=FALSE}
Importp4 <- data.frame(
    VALOR = 10000000,
    PESO = 20000000,
    VIA = 1,
    PAIS = 5404,
    ADUANA = 11,
    MES = 7,
    ANYO = 2024
)
```


```{r, eval=FALSE}
predic4 <- predict(tree4, Importp4, type = "prob")

cat("\n### PREDICCIÓN PARA PAIS ###\n")
cat("Valor de la importacion: 100,000 USD\n")
cat("- Peso de la importacion: 1,200 Kg\n")
cat("- Medio de Transporte: Aereo\n")
cat("- Aduana: Express Aereo\n")
cat("- Sac: Maquinas Herramienta(8465)\n")
cat("- Mes: Agosto\n")
cat("- Año: 2018\n")
cat("\n")

```

```{r, eval=FALSE}

cat("Probabilidades de Pais:\n")
print(round(predic4 * 100, 2))

# identificar la relación más probable
relacion_antic4 <- colnames(predic4)[which.max(predic4)]
prob_maxima4 <- max(predic4) * 100

cat("\nRelación más probable:", relacion_antic3)
cat("\nProbabilidad:", round(prob_maxima3, 2), "%\n")

```

**VARIABLE 5 EXPORTS**

```{r Arboles de Decision 5, eval=FALSE}
# EXploración inicials de la variable objetivo

cat("Distribución de PAIS:\n")
table(dataset_exports$PAIS)
cat("\n")

```

```{r, eval=FALSE}
# ÁRBOL DE DECISIÓN

# relación PAIS-EXPORTACIONES basado en:
# - características de la Exportacion (Valor, Peso, Via, Aduana, Pais, Mes y Año)
# - con esto, la prediccion sera mas soportada y nos dara informacion relevante.

tree5<- rpart(PAIS ~
              VALOR +
              PESO +
              VIA +
              ADUANA +
              SAC +
              MES +
              ANYO,
            data = dataset_exports, 
            method = "class",
            control = rpart.control(
              minsplit = 200,   
              minbucket = 100,  
              maxdepth = 4,    
              cp = 0.01
            ))

```



```{r, eval=FALSE}

rpart.plot(tree5, type = 2, extra = 0, under = TRUE, box.palette = "BuGn",
            main= "PAIS EXPORT", cex= 0.5)

#Para este grafico igualmente que imports, el arbol es grande, sin embargo, sigue siendo la Aduana quien domina como puntos de nodo dentro del arbol.

```

```{r, eval=FALSE}

#Evaluando el detalle del arbol.

cat("\nImportancia de las variables:\n")
print(tree5$variable.importance)

cat("\n---- RESUMEN DEL MODELO ----\n")
print(summary(tree5))

```


```{r, eval=FALSE}
#Se busca la prediccion para la siguiente exportacion

export5 <- data.frame(
    VALOR = 10000000,
    PESO = 50000000,
    VIA = 3,
    ADUANA = 11,
    SAC = 2940000000,
    MES = 3,
    ANYO = 2023
)
```


```{r, eval=FALSE}
predic5 <- predict(tree5, export5, type = "prob")

cat("\n### PREDICCIÓN PARA PAIS-EXPORT ###\n")
cat("Valor de la importacion: 10,000,000 USD\n")
cat("- Peso de la importacion: 50,000,000 Kg\n")
cat("- Medio de Transporte: Maritimo\n")
cat("- Aduana: Santo Tomas de Castilla\n")
cat("- Sac: Azucar\n")
cat("- Mes: Marzo\n")
cat("- Año: 2023\n")
cat("\n")

```

```{r, eval=FALSE}

cat("Probabilidades de Pais:\n")
print(round(predic5 * 100, 2))

# Relación más probable

relacion_antic5 <- colnames(predic5)[which.max(predic5)]
prob_maxima5 <- max(predic5) * 100

cat("\nRelación más probable:", relacion_antic5)
cat("\nProbabilidad:", round(prob_maxima5, 2), "%\n")

#La prediccion es que con una probabilidad del 27.91% este tipo de producto se exporta a Estados Unidos.

```


**VARIABLE 6**

```{r Arboles de Decision6, eval=FALSE}
# EXploración inicials de la variable objetivo

cat("Distribución de ADUANA:\n")
table(dataset_exports$ADUANA)
cat("\n")

```

```{r, eval=FALSE}
# ÁRBOL DE DECISIÓN

# relación ADUANA-EXPORTACIONES basado en:
# - características de la Exportacion (Valor, Peso, Via, Aduana, Pais, Mes y Año)
# - con esto, la prediccion sera mas soportada y nos dara informacion relevante.


tree6<- rpart(ADUANA ~
              VALOR +
              PESO +
              VIA +
              PAIS +
              SAC +
              MES +
              ANYO,
            data = dataset_exports, 
            method = "class",
            control = rpart.control(
              minsplit = 200,   
              minbucket = 100,  
              maxdepth = 4,    
              cp = 0.01
            ))

```

```{r, eval=FALSE}

rpart.plot(tree6, type = 2, extra = 0, under = TRUE, box.palette = "BuGn",
            main= "ADUANA EXPORT", cex= 0.5)

## Al igual que la importaciones, en exportaciones cuando se analiza o predice por medio de Aduana, la Via es la principal, sin embargo, hay una influencia en la ramas secundarias del Pais.

```



```{r, eval=FALSE}


cat("\nImportancia de las variables:\n")
print(tree6$variable.importance)

cat("\n---- RESUMEN DEL MODELO ----\n")
print(summary(tree6))

##Este analisis da la visibilidad de que el peso de la via y pais es muy cercano y son los que dominan al momento de aplicar este algoritmo.

```


```{r, eval=FALSE}

##Prediccion

exportp6 <- data.frame(
    VALOR = 425038,
    PESO = 142295,
    VIA = 1,
    PAIS = 1007,
    SAC = 102290000,
    MES = 4,
    ANYO = 2024
)
```


```{r, eval=FALSE}
predic6 <- predict(tree6, exportp6, type = "prob")

cat("\n### PREDICCIÓN PARA ADUANA ###\n")
cat("Valor de la importacion: 425,038 USD\n")
cat("- Peso de la importacion: 142,295 Kg\n")
cat("- Medio de Transporte: Terrestre\n")
cat("- Pais: Mexico\n")
cat("- Sac: Ganado Bovino\n")
cat("- Mes: Abril\n")
cat("- Año: 2024\n")
cat("\n")

```

```{r, eval=FALSE}

cat("Probabilidades de Pais:\n")
print(round(predic6 * 100, 2))

# Relación más probable

relacion_antic6 <- colnames(predic6)[which.max(predic6)]
prob_maxima6 <- max(predic6) * 100

cat("\nRelación más probable:", relacion_antic6)
cat("\nProbabilidad:", round(prob_maxima6, 2), "%\n")

##El resultado evidencia que la Aduana de Tecun Uman seria con un 97.61% la aduana usada para exportar Ganado a Mexico.

```

**RANDOM FOREST**

```{r, eval=FALSE}

##DEBIDO A LA CANTIDAD TAN GRANDE DE DATOS, MI EQUIPO NO LOGRO MANEJAR EL 100% POR LO QUE SE ESTABLECIO QUE SE HICIERA UNA REDUCCION EN LOS AÑOS, POR LO QUE SE LIMITA EL EL DATASET DEL 2018 AL 2020.

dataset_imports <- subset(dataset_imports, ANYO >=2018 & ANYO<= 2020)

datos <- dataset_imports[,c("PAIS", "SAC", "VALOR", "VIA", "ADUANA")]

datos$PAIS <- as.factor(datos$PAIS)

set.seed(100)

datos <- datos[sample(1:nrow(datos)),]

index <- sample(1:nrow(datos), 0.80*nrow(datos))


train <- datos[index,]
test <- datos[-index,]
train$PAIS <- droplevels(as.factor(train$PAIS))

## SE GENERA EL BOSQUE - Ejecucion 1 h - 44 min

forest1 <- randomForest(PAIS ~
                SAC +
                VALOR +
                VIA +
                ADUANA,  
                data = train, 
                ntree= 200,
                mtry = 3)

#Se diseña la prediccion:

prueba <- predict(forest1,test)
prueba

matriz <- table(test$PAIS, prueba)
matriz

# Se arma la importacion a predecir con base en el Random Forest

importt2 <- data.frame (
  SAC = c(9504),  #Consolas de Videojuegos
  VALOR = c(1000000),
  VIA = c(3), # Via maritima
  ADUANA = c(11) # Santo Tomas
  )

result3 <- predict(forest1,importt2, type="prob")
result3

# Las consolas de videojuego en un 95.5% se importan via miritima de Estados Unidos.

```
```{r, eval=FALSE}
#Se imprime el Random Forest

plot(forest1)


```

**RandomForest2**

```{r, eval=FALSE}

dataset_exports <- subset(dataset_exports, ANYO >=2020 & ANYO<= 2023)

datos2 <- dataset_exports[,c("PAIS", "SAC", "VALOR", "VIA", "ADUANA")]

datos2$VIA <- as.factor(datos2$VIA)

set.seed(100)

datos2 <- datos2[sample(1:nrow(datos2)),]

index <- sample(1:nrow(datos2), 0.85*nrow(datos2))


train2 <- datos2[index,]
test2 <- datos2[-index,]


forest2 <- randomForest(VIA ~
                SAC +
                VALOR +
                PAIS +
                ADUANA,  
                data = train2, 
                ntree= 200,
                mtry = 4)


prueba2 <- predict(forest2,test2)
prueba2

matriz2 <- table(test2$VIA, prueba2)
matriz2


# SE CREA LA EXPORTACION DONDE SE BUSCA PREDECIR LA VIA

export2 <- data.frame (
  SAC = c(2710192200), # BUNKER C - PARA LA INDUSTRIA ENERGETICA
  VALOR = c(10000000), 
  PAIS = c(3507), #Se sabe que Peru es cliente actual de Guatemala.
  ADUANA = c(15)
  )

resultex <- predict(forest2,export2, type="prob")
resultex



```



```{r, eval=FALSE}

#Se imprime el RF

plot(forest2)


```

**RandomForest3**

```{r, eval=FALSE}

dataset_imports <- subset(dataset_imports, ANYO >=2021 & ANYO<= 2024)

datos3 <- dataset_imports[,c("PAIS", "SAC", "VALOR", "VIA", "ADUANA")]
datos3 <- na.omit(datos3)

top_sac <- names(sort(table(datos3$SAC), decreasing = TRUE))[1:100]
datos3 <- datos3 %>% filter(SAC %in% top_sac)
datos3$SAC <- droplevels(as.factor(datos3$SAC))

set.seed(100)

datos3 <- datos3[sample(1:nrow(datos3)),]

index1 <- sample(1:nrow(datos3), 0.80*nrow(datos3))

train3 <- datos3[index1,]
test3 <- datos3[-index1,]

train3$SAC <- droplevels(train3$SAC)
test3$SAC <- droplevels(test3$SAC)

forest3 <- randomForest(SAC ~
                VIA +
                VALOR +
                PAIS +
                ADUANA,  
                data = train3, 
                ntree= 200,
                mtry = 3)

prueba3 <- predict(forest3,test3)
prueba3

matriz3 <- table(test3$SAC, prueba3)
matriz3


#SE CREA LA IMPORTACION A PREDECIR

import3 <- data.frame (
  VIA = c(1),
  VALOR = c(1000000), #EN USD
  PAIS = c(1005), # ESTADOS UNIDOS
  ADUANA = c(31)  # Tecun Uman
  )

resultim1 <- predict(forest3,import3, type="prob")
resultim1


```



```{r, eval=FALSE}

#Se Grafica el RF

plot(forest3)


```









